# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "graphsage"
  input_dim: 1433
  hidden: 128
  dropout: 0.5
  nb_heads: 20
  alpha: 0.2


###################
## Dataset options
dataset_params:
  dataset_type: "cora"
  save_results: "graphsage_cora/detect"
  


###################
## Data_loader options
train_data_loader:
  data_path: "E:\\Freelance_projects\\GNN\\Tuts\\pyGNN\\src\\dataset\\citation_base\\cora\\"
  imageset: "train"
  return_ref: True
  batch_size: 64
  shuffle: True
  num_workers: 2

val_data_loader:
  data_path: "E:\\Freelance_projects\\GNN\\Tuts\\pyGNN\\src\\dataset\\citation_base\\cora\\"
  imageset: "val"
  return_ref: True
  batch_size: 64
  shuffle: False
  num_workers: 4


test_data_loader:
  data_path: "E:\\Freelance_projects\\GNN\\Tuts\\pyGNN\\src\\dataset\\citation_base\\cora\\"
  imageset: "val"
  return_ref: True
  batch_size: 1
  shuffle: False
  num_workers: 4


###################
## Train params
train_params:
  model_load_path: "E:\\Freelance_projects\\GNN\\Tuts\\pyGNN\\weights\\"
  model_save_path: "E:\\Freelance_projects\\GNN\\Tuts\\pyGNN\\weights\\"
  checkpoint_every_n_steps: 100
  max_num_epochs: 200
  patience: 500
  lr_rate: 0.001
  seed: 42  
  validationmode: False
  weight_decay: 0.0005 
  save_fig: True 
  save_log: True
###################
## Test params
test_params:
  model_load_path: "E:\\Freelance_projects\\GNN\\Tuts\\GNN_Tuts\\weigths\\"
  model_save_path: "E:\\Freelance_projects\\GNN\\Tuts\\GNN_Tuts\\weigths\\"
  output_viz: True
 