
---



# -------------------------------------------------------------------
    Data:         # Use Cora dataset training model
        datatype:           'pubmed'  # Type of the citation data 
        save_results:       "gwnn_pubmed/detect" # Folder name to save the results 
        datapath :          "E:\\Freelance_projects\\GNN\\Tutsv2\\pyGNN_NC_XAI_V2\\src\\dataset\\citation_pre\\"   #Input data path for loading data
        model_save_path:    "E:\\Freelance_projects\\GNN\\Tutsv2\\pyGNN_NC_XAI_V2\\weights"  # Path to save the weight file 
        save_fig:           True  # Saving of the training and validation plot  
        output_viz:         True  # saving the results output     
# -------------------------------------------------------------------
    random_state :      42           # random seed
    'gwnn' :                         # dropedge parameter
        type :             'gwnn'               # type of base network
    Model :  
        type:           'gwnn'                       # model parameters
        use_bn :        false          # whether to use batch normalization
        dropout :       0.5            # dropout ratio
        input_dim :     1433           # node feature dimensions
        hidden_dim :    16             # hidden layer output characteristic dimension
        output_dim :    7              # number of nodes category
        approximation_order: 4
        scale:    1.0 #Scaling parameter. Default is 1.0.
        threshold:    0.0001 #Sparsification parameter. Default is 1e-4.
        fastmode:   True #args.fast #args.fast
        
    Hyper :                         # training hyperparameter
        LR :            0.001           # optimizer initial learning rate
        epochs :        4          # training rounds
        Patience :      800            # stopped early rounds
        weight_decay :  0.0005         # optimizer weight decay
        batch_size:     8             # batch size for dataloading 


...