---



# -------------------------------------------------------------------
    Data:         # Use Cora dataset training model
        datatype:           'cora'              # To provide the type of data to load 
        save_results:       "spgat_cora/detect"          #provide path to save the results 
        datapath :          "E:\\Freelance_projects\\GNN\\Tutsv2\\pyGNN_NC_XAI_V2\\src\\dataset\\citation_pre\\"   # to provide dataset loading path 
        model_save_path:    "E:\\Freelance_projects\\GNN\\Tutsv2\\pyGNN_NC_XAI_V2\\weights"    # To provide the model save path 
        save_fig:           True        # To save the figure option 
        output_viz:         True        #  To display the output option         
# -------------------------------------------------------------------
    random_state :      42              # random seed
    gat :                               # dropedge parameter
        type :          'sp_gat'        # type of base network 
        
    Model :                             # model parameters
        use_bn :        false           # whether to use batch normalization
        dropout :       0.5             # dropout ratio
        input_dim :     1433            # node feature dimensions
        hidden_dim :    8             # hidden layer output characteristic dimension
        output_dim :    7               # number of nodes category
        nbheads:   8
        
        

    Hyper :                         # training hyperparameter
        LR :            0.001       # optimizer initial learning rate
        epochs :        100         # training rounds
        Patience :      400         # stopped early rounds
        weight_decay : 0.0005       # optimizer weight decay
        dropout:    0.5             # Dropout parameter 
        alpha:   0.2                # alpha value
        num_workers: 1
        batch_size: 1

    Logger:
        output_viz: True
        save_fig: True 
        save_log: True

...