---

# -------------------------------------------------------------------
    Data:         # Use Cora dataset training model
        datatype:           'cora'              # To provide the type of data to load 
        save_results:       "fastgcn_cora/detect"          #provide path to save the results 
        datapath :          "E:\\Freelance_projects\\GNN\\Tutsv2\\pyGNN_NC\\src\\dataset\\citation_pre\\"   # to provide dataset loading path 
        model_save_path:    "E:\\Freelance_projects\\GNN\\Tutsv2\\pyGNN_NC\\weights"    # To provide the model save path 
        save_fig:           True    # To save the figure option 
        output_viz:         True    #  To display the output option         
# -------------------------------------------------------------------
    random_state :      42           # random seed
    gcn :                         # dropedge parameter
        type :             'fastgcn'               # type of base network 
        
    Model :                         # model parameters
        use_bn :        false          # whether to use batch normalization
        dropout :       0.5            # dropout ratio
        input_dim :     1433           # node feature dimensions
        hidden_dim :    16             # hidden layer output characteristic dimension
        output_dim :    7              # number of nodes category

    Hyper :                         # training hyperparameter
        LR :            0.001           # optimizer initial learning rate
        epochs :        8           # training rounds
        Patience :      400            # stopped early rounds
        weight_decay : 0.0005         # optimizer weight decay
        dropout:        0.5                # Dropout parameter 
        batch_size:   2             # loading data batchsize 

...